### ISSUE TITLE
#1 Weekly – December 14, 2018

### ISSUE THREAD

**Issue by kamranahmedse** [me-io/newsletter#1]
<div class="main" id="main" style="max-width: 600px;"><h1 align="center">Dev Newsletter - me.io</h1><h3>What's Trending?</h3><hr width="100%"></hr><table><tr><td><a href="https://blog.npmjs.org/post/180868064080/this-year-in-javascript-2018-in-review-and-npms" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/3f017fdc-0ad7-4cb5-a9b9-b75e318b9332/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://blog.npmjs.org/post/180868064080/this-year-in-javascript-2018-in-review-and-npms" target="_blank">This year in JavaScript: 2018 in review and npm’s predictions for 2019</a> JavaScript is the world’s most programming language, npm plays host to over 800,000 libraries, GraphQL’s popularity is booming, and the most popular other languages JavaScript developers use are Java, PHP and Python
                        </td></tr><tr><td><a href="https://babeljs.io/blog/2018/12/03/7.2.0" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/453c9a5e-c0e7-4831-8a21-385fb31dfa47/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://babeljs.io/blog/2018/12/03/7.2.0" target="_blank">Babel 7.2.0 Released with Private Instance Methods</a> There’s a proposal for JavaScript to support private instance methods and variables (by prefixing their names with #) and Babel already supports it as seen here
                        </td></tr><tr><td><a href="https://overreacted.io" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/76faabc8-1435-4dd9-b597-d6040dafc5ee/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://overreacted.io" target="_blank">Overreacted: Blog by React Expert Dan Abramov</a> Dan recently created his blog and already has shared some really informative articles about the react internals.
                        </td></tr></table><h3>Articles</h3><hr width="100%"></hr><table><tr><td><a href="https://blog.cloudflare.com/head-start-with-quic/" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/2e9ebaff-dc3f-4670-9830-e26c32c32722/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://blog.cloudflare.com/head-start-with-quic/" target="_blank">QUIC (aka HTTP/3)</a> Google QUIC protocol is to become the HTTP/3, with so many changes and improvements, moving from TCP to UDP and having a MobileIP!
                        </td></tr><tr><td><a href="https://www.tomasvotruba.cz/blog/2018/08/16/whats-new-in-php-73-in-30-seconds-in-diffs/#what-s-new-in-php-7-3-in-30-seconds-in-diffs" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/8293f71c-75c2-4f20-b15a-d07d4a9afb67/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://www.tomasvotruba.cz/blog/2018/08/16/whats-new-in-php-73-in-30-seconds-in-diffs/#what-s-new-in-php-7-3-in-30-seconds-in-diffs" target="_blank">What's New in PHP 7.3 in 30 Seconds in Diffs</a> No time but eager to hear PHP news? PHP 7.3 is out in December 2018 and it brings 173 changes. Which are the most useful ones?
                        </td></tr><tr><td><a href="https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/c74afe9f-5607-435f-9d35-59f023aeeb40/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70" target="_blank">Modern JavaScript Explained For Dinosaurs</a> A modern JavaScript in a nutshell. How it evolved from plan HTML and JS to using a package manager to automatically download 3rd party packages, a module bundler to create a single script file, a transpiler to use future JavaScript features, and a task runner to automate different parts of the build process.
                        </td></tr><tr><td><a href="https://www.youtube.com/watch?v=aNZ3Vwmf_V8" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/f193e4e5-d94d-434b-ae9c-98faa3b808fb/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://www.youtube.com/watch?v=aNZ3Vwmf_V8" target="_blank">React Hooks Explained - Functional Components With State</a> A primer on how to use hooks in react
                        </td></tr></table><h3>Code and Tools</h3><hr width="100%"></hr><table><tr><td><a href="https://github.com/MrRio/jsPDF" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/591f89f7-c6b7-49b2-ac5e-c978c6f5a76f/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/MrRio/jsPDF" target="_blank">PDF generator that works in the browser</a> Client-side JavaScript PDF generation for everyone
                        </td></tr><tr><td><a href="https://github.com/lovell/sharp" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/c956dda8-a6c6-4f23-b28d-a2ad1045379f/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/lovell/sharp" target="_blank">High Performance Node.js image processing library</a> High performance Node.js image processing, the fastest module to resize JPEG, PNG, WebP and TIFF images.
                        </td></tr><tr><td><a href="https://github.com/wagoodman/dive" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/370a790b-b71f-4380-8347-46092602126f/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/wagoodman/dive" target="_blank">Docker – Inspect layers of your Docker Image</a> A tool written in Golang to explore each layer in a docker image
                        </td></tr></table><h3>Releases</h3><hr width="100%"></hr><table><tr><td><a href="https://themeisle.com/blog/wordpress-5-0/" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/341854e7-2206-4160-8bfa-c24f3e8c1d39/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://themeisle.com/blog/wordpress-5-0/" target="_blank">Wordpress 5.0 'Bebo'</a> New version of Wordpress comes with long-anticipated Gutenberg editor, some improvements to the RESTful API and makes building custom themes easier.
                        </td></tr><tr><td><a href="https://nodejs.org/en/blog/release/v11.4.0/" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/ae25dac7-202a-4c02-af08-995a3eca821d/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://nodejs.org/en/blog/release/v11.4.0/" target="_blank">Node.js 11.4.0</a> Minor release – Look at the link for further details
                        </td></tr><tr><td><a href="https://github.com/angular/angular/blob/master/CHANGELOG.md#712-2018-12-06" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/f135d6d6-e542-49f7-936c-f90e40c5f16e/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/angular/angular/blob/master/CHANGELOG.md#712-2018-12-06" target="_blank">Angular 7.1.2</a> Patch Release for Angular
                        </td></tr><tr><td><a href="https://github.com/Microsoft/TypeScript/releases/tag/v3.2.2" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/1717c294-ba63-4df8-9d6d-4c1206007167/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/Microsoft/TypeScript/releases/tag/v3.2.2" target="_blank">TypeScript 3.2.2</a> Patch Release for TypeScript
                        </td></tr><tr><td><a href="https://github.com/webpack/webpack/releases/tag/v4.27.0" target="_blank"><img align="left" height="50" src="https://ucarecdn.com/1d7eb69b-efb8-41a6-85b2-e19773b624b5/-/resize/100x50/" style="padding-right: 20px;" width="100"></img></a><a href="https://github.com/webpack/webpack/releases/tag/v4.27.0" target="_blank">Webpack 4.27.0</a> Minor Release for Webpack
                        </td></tr></table><p align="center"><small>Made with ❤ in DXB - { vol. 1 }</small></p><p align="center"><small><a href="https://me.io/subscribe-to-our-newsletter" target="_blank">Subscribe to our newsletter and
                    don't miss out any news</a></small></p><p align="center"><small>
                Thank you for reading, special thanks to {
                                    <a href="https://twitter.com/kamranahmedse" target="_blank">kamran</a> -                                     <a href="https://twitter.com/meabed" target="_blank">meabed</a>                                } - for contributing to the newsletter.
            </small></p><p align="center"><small><a href="https://github.com/me-io/community" target="_blank">Join us in the Meetup</a> - <a href="https://github.com/me-io/newsletter" target="_blank">Share and contribute
                    to the next newsletter</a></small></p></div>

**Comment by blyndusk** [comment]
We could talk about this event, which aims to push and help the community to contribute open source projects, in the same perspective as this newsletter

**[24 Pull Request](https://24pullrequests.com/)**
An event to make the contribution to open-source projects more accessible and understandable
*Event*

**Comment by Idnan** [comment]
**[HTTPS in the real world](https://robertheaton.com/2018/11/28/https-in-the-real-world/)**
HTTPS in the real world
*Article*

**[What's New in PHP 7.3 in 30 Seconds in Diffs](https://www.tomasvotruba.cz/blog/2018/08/16/whats-new-in-php-73-in-30-seconds-in-diffs/#what-s-new-in-php-7-3-in-30-seconds-in-diffs)**
No time but eager to hear PHP news? PHP 7.3 is out in December 2018 and it brings 173 changes. Which are the most useful ones?
*News*

**[Modern JavaScript Explained For Dinosaurs](https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70)**
A modern JavaScript in a nutshell. How it evolved from plan HTML and JS to using a package manager to automatically download 3rd party packages, a module bundler to create a single script file, a transpiler to use future JavaScript features, and a task runner to automate different parts of the build process.
*Article*

**Comment by kamranahmedse** [comment]
**[Wordpress 5.0 "Bebo" Released](https://themeisle.com/blog/wordpress-5-0/)**
New version of Wordpress comes with long-anticipated Gutenberg editor, some improvements to the RESTful API and makes building custom themes easier.
*Release*

**[Angular 7.1.2](https://github.com/angular/angular/blob/master/CHANGELOG.md#712-2018-12-06)**
Patch Release for Angular
*Release*

**[TypeScript 3.2.2](https://github.com/Microsoft/TypeScript/releases/tag/v3.2.2)**
Patch Release for TypeScript
*Release*

**[Ember.js 3.6.0](https://github.com/emberjs/ember.js/releases/tag/v3.6.0)**
Minor Release for Ember
*Release*

**[Webpack 4.27.0](https://github.com/webpack/webpack/releases/tag/v4.27.0)**
Minor Release for Webpack
*Release*
